spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: nizar
    password: nizar123
    driver-class-name: oracle.jdbc.OracleDriver
  security:
    user:
      name: nizar
      password: 1234




